# Generated by Django 3.2.6 on 2022-05-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUsers',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id_user', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25, unique=True, verbose_name='Introduzca su GamerTag')),
                ('password', models.CharField(max_length=25, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Introduzca su Email')),
                ('img_perfil', models.ImageField(default='users/default.png', upload_to='users/')),
                ('ganadas', models.PositiveIntegerField(default=0)),
                ('perdidas', models.PositiveIntegerField(default=0)),
                ('user_gamer', models.BooleanField(default=True)),
                ('user_admin', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
    ]
