# Generated by Django 3.2.6 on 2022-05-29 14:21

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gameusers',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
