# Generated by Django 3.1.14 on 2022-06-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220604_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameusers',
            name='password',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
