# Generated by Django 3.1.14 on 2022-06-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220604_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameusers',
            name='last_login',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
