# Generated by Django 3.1.14 on 2022-06-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220604_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameusers',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
