# Generated by Django 3.1.14 on 2022-06-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220604_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameusers',
            name='perdidas',
        ),
        migrations.AddField(
            model_name='gameusers',
            name='sala_predefinida',
            field=models.PositiveIntegerField(auto_created=True, default=0, unique=True),
            preserve_default=False,
        ),
    ]
