# Generated by Django 3.1.14 on 2022-06-06 08:23

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220606_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameusers',
            name='sala_predefinida',
            field=models.PositiveIntegerField(default=users.models.GameUsers.contador, unique=True),
        ),
    ]
