# Generated by Django 3.2.6 on 2022-05-29 13:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tictactoe', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe',
            name='jugador_O',
            field=models.ForeignKey(on_delete=models.SET('Usuario eliminado'), related_name='gamertag_O', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tictactoe',
            name='jugador_X',
            field=models.ForeignKey(on_delete=models.SET('Usuario eliminado'), related_name='gamertag_X', to=settings.AUTH_USER_MODEL),
        ),
    ]
