# Generated by Django 3.1.14 on 2022-06-04 10:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe',
            name='tablero_O',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default='', max_length=6, size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tictactoe',
            name='tablero_X',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default='', max_length=6, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='resultado',
            field=models.CharField(choices=[('X', 'El jugador X gano la partida'), ('O', 'El jugador O gano la partida'), ('T', 'La partida acabo en tablas'), ('P', 'La partida sigue en curso')], default='P', max_length=1),
        ),
    ]
