# Generated by Django 3.1.14 on 2022-06-04 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0003_auto_20220604_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe',
            name='sala_cod',
            field=models.PositiveIntegerField(default=0, unique=True, validators=[django.core.validators.MaxValueValidator(9999)]),
            preserve_default=False,
        ),
    ]
