# Generated by Django 3.1.14 on 2022-06-04 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tictactoe', '0004_tictactoe_sala_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='jugador_O',
            field=models.ForeignKey(on_delete=models.SET('Usuario eliminado'), related_name='gamertag_O', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='jugador_X',
            field=models.ForeignKey(on_delete=models.SET('Usuario eliminado'), related_name='gamertag_X', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
