# Generated by Django 3.1.14 on 2022-06-05 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0005_auto_20220604_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='jugador_O',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='jugador_X',
            field=models.CharField(max_length=25),
        ),
    ]
