# Generated by Django 3.1.14 on 2022-06-05 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0008_auto_20220605_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tictactoe',
            name='tablero_O',
        ),
        migrations.RemoveField(
            model_name='tictactoe',
            name='tablero_X',
        ),
    ]
