# Generated by Django 3.1.14 on 2022-06-05 07:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tictactoe', '0009_auto_20220605_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tictactoe',
            name='tablero',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='jugador_O',
            field=models.ForeignKey(on_delete=models.SET('Usuario eliminado'), related_name='gamertag_O', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='jugador_X',
            field=models.ForeignKey(on_delete=models.SET('Usuario eliminado'), related_name='gamertag_X', to=settings.AUTH_USER_MODEL),
        ),
    ]
