# Generated by Django 3.1.14 on 2022-06-05 15:50

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0011_auto_20220605_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tictactoe',
            name='id_game',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='resultado',
            field=models.CharField(choices=[('X', 'El jugador X gano la partida'), ('O', 'El jugador O gano la partida'), ('T', 'La partida acabo en tablas'), ('P', 'La partida sigue en curso'), ('I', 'La partida la ha iniciado un jugador, a la espera del rival.'), ('D', 'Un jugador se ha desconectado, a la espera de que vuelva.')], default='I', max_length=1),
        ),
        migrations.AlterField(
            model_name='tictactoe',
            name='sala_cod',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
